config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :posts do
  	member do
  		post 'favs'
  	end
  	collection do
  		post 'fav'
  	end
  end
  resources :users
  get 'welcome/index'

	mount Sidekiq::Web => '/sidekiq'

  mount WeixinRailsMiddleware::Engine, at: "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
end

app/models/category.rb
class Category
  include Mongoid::Document
  # include Mongoid::Tree
  field :name, type: String
  has_many :children, class_name: 'Category', inverse_of: :parent

  belongs_to :parent, class_name: 'Category', inverse_of: :children
  # 判断是否是字节点
  def child?
  # 当前自己的父节点不为空
    self.parent != nil
  end
  # 判断是否是父节点
  def root?
  # 当前自己的父节点等于空
    self.parent == nil
  end
  # 拿到自己的所有父节点
  def self.roots
  # 自己里面父节点等于空的就是父节点
    where(parent: nil)
  end
  # 拿到所有的子节点
  def self.children
  # 
    where(:parent.ne => nil)
  end
end

app/models/log.rb
class Log # 签到
  include Mongoid::Document
  include Mongoid::Timestamps
  # 积分
  field :credit, type: Integer
  belongs_to :user # 积分属于用户
end

app/models/post.rb
class Post
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
  field :likes, type: Integer, default: 0 #点赞数
  belongs_to :user
 
    # 点赞方法，传入一个用户对象
  def liked(user)
    # 如果在集合中添加ID成功
    if $redis.sadd "post:#{self.id.to_s}:likers", user.id.to_s
      # 那么点赞数+1  
      self.inc(likes: 1)
      # 点赞成功状态变成1，返回消息点赞成功
      {status: 1, notice: '点赞成功'}
    else
      # 否则返回状态-1，返回消息重复点赞
      {status: -1, notice: '重复点赞'}
    end
  end
  # 查看点赞的所有人
  def likers
    user_ids = $redis.smembers "post:#{self.id.to_s}:likers"
    User.find(user_ids)
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :nickname, type: String
  field :openid, type: String
  field :headimgurl, type: String
  field :credit, type: Integer, default: 0  # 积分
  has_many :posts
  has_many :logs 

  validates :nickname, presence: true

# 签到功能
  def sign_in
  	# 判断如果在签到中里面找到签到创建时间是在今天范围内的话
    if self.logs.between(created_at: [Date.today.beginning_of_day, Date.today.end_of_day]).any?
      # 返回状态 -1，提示你已经签到过了，请明天再来
      {status: -1, notice: '你已经签到过了，请明天再来！'}
    else
    	# 否者签到积分增加3
      self.inc(credit: 3)
      # 创建用户签到表，里面积分为3分保存起来
      self.logs.create(credit: 3)
      # 返回状态为1，
      {status: 1, notice: '恭喜你签到成功', credit: 3}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :openid, :headimgurl)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	# 访问index页面发送请求创建自定义菜单
  	menu = {
     "button":[
     {    
          "type": "click",
          "name": "签到",
          "key": "SIGN_IN" 
      },
      {
           "name": "菜单",
           "sub_button": [
            {
              "type": "view",
              "name": "今日热点",
              "url": "https://www.toutiao.com/"
              },
           {    
               "type": "view",
               "name": "搜索",
               "url": "http://www.baidu.com/"
            },
            {
              "type": "view",
              "name": "🎲损友圈",
              "url": "http://play.wxavu.com/game/?gameid=261&share_from=msg&fuid=311379278&statid=1602&cp_from=msg&cp_shareId=41/"
            },
            {
               "type": "click",
               "name": "点赞",
               "key": "LIKE"
            }]
     },
     { 
       	   "name": "关于我",
    		   "sub_button":[
          	{
    		       "type": "click",
    		       "name": "查看点赞数",
    		       "key": "LIKE_COUNT"
    				
    	      },
            {
              "type": "click",
              "name": "联系我们",
              "key": "CONNECT_US"
            },
            {	
        	    "type": "click",
        	    "name": "个人中心",
        	    "key": "USER"
            },
            {
              "type": "click",
              "name": "其他",
              "key": "OTHER"

              }]
     }
       ]
 }

   	response = $client.create_menu(menu) # Hash or Json
   	# 响应输出在页面显示出来
    logger.debug response 
    # 返回json格式的响应
		render json: response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :user_nickname %>
  </div>

  <div class="field">
    <%= form.label :openid %>
    <%= form.text_field :openid, id: :user_openid %>
  </div>

  <div class="field">
    <%= form.label :headimgurl %>
    <%= form.text_field :headimgurl, id: :user_headimgurl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Openid</th>
      <th>Headimgurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.openid %></td>
        <td><%= user.headimgurl %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Openid:</strong>
  <%= @user.openid %>
</p>

<p>
  <strong>Headimgurl:</strong>
  <%= @user.headimgurl %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= weixin_engine.weixin_server_url('6b27b955568af855dbaceccf4e775d26') %>